import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Sample blog website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <h1 className='mt-8 mb-4 justify-center'>
          Welcome to my blog, using Next.js!
        </h1>

        <p>Get started by exploring site and see all the features</p>
      </div>
    </>
  );
}
